export const clerkAppearance = {
  variables: {
    colorPrimary: "#a7c3ff",
    colorBackground: "#0a1222",
    colorInputBackground: "rgba(255, 255, 255, 0.05)",
    colorInputText: "#f8fafc",
    colorText: "#f8fafc",
    colorTextSecondary: "#94a3b8",
    colorNeutral: "#f8fafc",
    borderRadius: "1rem",
    fontFamily: "var(--font-manrope), sans-serif",
  },
  elements: {
    cardBox: "!shadow-[0_24px_120px_rgba(0,0,0,0.34)]",
    card: "!border !border-white/10 !bg-[#0a1222]",
    headerTitle: "!text-white",
    headerSubtitle: "!text-slate-300",
    socialButtonsBlockButton: "!border-white/10 !bg-white/5 !text-white hover:!bg-white/10",
    socialButtonsBlockButtonText: "!text-white",
    dividerLine: "!bg-white/10",
    dividerText: "!text-slate-400",
    formFieldLabel: "!text-slate-200",
    formFieldInput: "!border-white/12 !bg-white/5 !text-white placeholder:!text-slate-500",
    formFieldInputShowPasswordButton: "!text-slate-300",
    formFieldAction: "!text-[#a7c3ff] hover:!text-[#8fb0ff]",
    formFieldErrorText: "!text-rose-300",
    formFieldSuccessText: "!text-[#dbe6ff]",
    otpCodeFieldInput:
      "!border-white/15 !bg-white/5 !text-white focus:!border-[#a7c3ff] focus:!ring-[#a7c3ff]/25",
    formResendCodeLink: "!text-[#a7c3ff] hover:!text-[#8fb0ff]",
    backLink: "!text-[#a7c3ff] hover:!text-[#8fb0ff]",
    formButtonPrimary: "!bg-[#a7c3ff] !text-slate-950 hover:!bg-[#8fb0ff]",
    identityPreviewText: "!text-white",
    identityPreviewEditButton: "!text-[#a7c3ff]",
    footer: "!border-white/10 !bg-[#0d1628]",
    footerActionText: "!text-slate-400",
    footerActionLink: "!text-[#a7c3ff] hover:!text-[#8fb0ff]",
  },
} as const;
