export const clerkAppearance = {
  variables: {
    colorPrimary: "#2563eb",
    colorBackground: "#ffffff",
    colorInputBackground: "#f8fafc",
    colorInputText: "#0f172a",
    colorText: "#0f172a",
    colorTextSecondary: "#64748b",
    colorNeutral: "#0f172a",
    borderRadius: "1rem",
    fontFamily: "var(--font-manrope), sans-serif",
  },
  elements: {
    cardBox: "!shadow-[0_24px_80px_rgba(15,23,42,0.16)]",
    card: "!border !border-slate-200 !bg-white",
    headerTitle: "!text-slate-950",
    headerSubtitle: "!text-slate-600",
    socialButtonsBlockButton: "!border-slate-300 !bg-white !text-slate-800 hover:!bg-slate-50",
    socialButtonsBlockButtonText: "!text-slate-800",
    dividerLine: "!bg-slate-200",
    dividerText: "!text-slate-500",
    formFieldLabel: "!text-slate-700",
    formFieldInput: "!border-slate-300 !bg-slate-50 !text-slate-950 placeholder:!text-slate-400",
    formFieldInputShowPasswordButton: "!text-slate-600",
    formFieldAction: "!text-blue-600 hover:!text-blue-700",
    formFieldErrorText: "!text-red-600",
    formFieldSuccessText: "!text-emerald-600",
    otpCodeFieldInput:
      "!border-slate-300 !bg-slate-50 !text-slate-950 focus:!border-blue-600 focus:!ring-blue-600/20",
    formResendCodeLink: "!text-blue-600 hover:!text-blue-700",
    backLink: "!text-blue-600 hover:!text-blue-700",
    formButtonPrimary: "!bg-blue-600 !text-white hover:!bg-blue-700",
    identityPreviewText: "!text-slate-950",
    identityPreviewEditButton: "!text-blue-600",
    footer: "!border-slate-200 !bg-slate-50",
    footerActionText: "!text-slate-500",
    footerActionLink: "!text-blue-600 hover:!text-blue-700",
  },
} as const;
